# File: mond-test-redis-deployment.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mond-test-redis
  labels:
    app: mond
    env: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mond
      tier: redis
      env: test
  template:
    metadata:
      labels:
        app: mond
        tier: redis
        env: test
    spec:
      containers:
        - name: redis
          image: redis:6
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: redis-data
              mountPath: /data
      volumes:
        - name: redis-data
          persistentVolumeClaim:
            claimName: mond-test-pvc
